/* This file was generated by syncqt. */
#ifndef QT_ACTIVEQT_VERSION_H
#define QT_ACTIVEQT_VERSION_H

#define ACTIVEQT_VERSION_STR "5.15.11"

#define ACTIVEQT_VERSION 0x050F0B

#endif // QT_ACTIVEQT_VERSION_H
