/* This file was generated by syncqt. */
#ifndef QT_QT3DQUICK_VERSION_H
#define QT_QT3DQUICK_VERSION_H

#define QT3DQUICK_VERSION_STR "5.15.11"

#define QT3DQUICK_VERSION 0x050F0B

#endif // QT_QT3DQUICK_VERSION_H
